### ISSUE TITLE
Error saat download audio/video

### ISSUE THREAD

**Issue by XstepAhead** [Zacros-Team/ZacrosBot#3]
Error in uploading to media-xsp1-1.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...

**Comment by XstepAhead** [comment]
sama owner gabisa kebaca tulisannnya tidak bisa membaca vcard ini

**Comment by Azyansah** [comment]
> Error in uploading to media-xsp1-1.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...

Errornya waktu nge command apa ya bang kalo boleh tau?

**Comment by Azyansah** [comment]
> sama owner gabisa kebaca tulisannnya tidak bisa membaca vcard ini

Coba set ownernumbernya `"628xxxxxx"`
Soalnya kalo `"08xxxxxxx"` error bang

**Comment by XstepAhead** [comment]
> > Error in uploading to media-xsp1-1.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...
> 
> Errornya waktu nge command apa ya bang kalo boleh tau?

Setiap ada media yang di upload aja bang 
Sama asupan menu 
Jepang, hijab sama thailand ga bisa

**Comment by XstepAhead** [comment]
> > sama owner gabisa kebaca tulisannnya tidak bisa membaca vcard ini
> 
> Coba set ownernumbernya `"628xxxxxx"` Soalnya kalo `"08xxxxxxx"` error bang

Oke siap di coba

**Comment by XstepAhead** [comment]
app[worker.1]: (node:29) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
2021-12-18T00:14:30.751126+00:00 app[worker.1]:     at y2mateA (/app/lib/plugins/y2mate.js:80:49)
2021-12-18T00:14:30.751127+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-12-18T00:14:30.751127+00:00 app[worker.1]:     at async Object.cmd.on.query [as callback] (/app/lib/command/downloader.js:4:93)
2021-12-18T00:14:30.751128+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-12-18T00:14:30.751171+00:00 app[worker.1]: (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-12-18T00:14:30.751189+00:00 app[worker.1]: (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Azyansah** [comment]
> > > Error in uploading to media-xsp1-1.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...
> > 
> > 
> > Errornya waktu nge command apa ya bang kalo boleh tau?
> 
> Setiap ada media yang di upload aja bang Sama asupan menu Jepang, hijab sama thailand ga bisa

dah bang

**Comment by Azyansah** [comment]
> app[worker.1]: (node:29) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null 2021-12-18T00:14:30.751126+00:00 app[worker.1]: at y2mateA (/app/lib/plugins/y2mate.js:80:49) 2021-12-18T00:14:30.751127+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:95:5) 2021-12-18T00:14:30.751127+00:00 app[worker.1]: at async Object.cmd.on.query [as callback] (/app/lib/command/downloader.js:4:93) 2021-12-18T00:14:30.751128+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created) 2021-12-18T00:14:30.751171+00:00 app[worker.1]: (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) 2021-12-18T00:14:30.751189+00:00 app[worker.1]: (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

kalo itu salah di result sih bang, jadi ga terlalu ngaruh banyak
jadi kalo error coba lagi mungkin bisa
